<?php
// 工具注册表（由 nav.html 提取生成，勿手改结构）
// 结构: [ ['cat'=>分类名, 'items'=>[['url'=>..., 'name'=>..., 'accent'=>...], ...]], ... ]
return [
    [
        'cat' => 'JSON工具',
        'items' => [
            ['url' => '/json/', 'name' => 'Json格式化', 'accent' => ''],
            ['url' => '/jsonudview/', 'name' => 'Json格式化(上下)', 'accent' => ''],
            ['url' => '/jsonlrview/', 'name' => 'Json格式化(左右)', 'accent' => ''],
            ['url' => '/jsonzip/', 'name' => 'Json在线压缩转义', 'accent' => ''],
            ['url' => '/json2cs/', 'name' => 'Json生成C#实体类', 'accent' => ''],
            ['url' => '/json2java/', 'name' => 'Json生成Java实体类', 'accent' => ''],
            ['url' => '/json2go/', 'name' => 'Json生成Go结构体', 'accent' => ''],
            ['url' => '/sql2java/', 'name' => 'SQL转Java实体类', 'accent' => ''],
            ['url' => '/json2xml/', 'name' => 'XML和Json在线互转', 'accent' => ''],
            ['url' => '/excel2json/', 'name' => 'Excel/CSV转Json格式', 'accent' => ''],
            ['url' => '/json2excel/', 'name' => 'Json转Excel/CSV格式', 'accent' => ''],
            ['url' => '/json2get/', 'name' => 'JSON和GET参数互转', 'accent' => ''],
            ['url' => '/json2yaml/', 'name' => 'JSON转YAML', 'accent' => ''],
        ],
    ],
    [
        'cat' => '格式化转换',
        'items' => [
            ['url' => '/formathtml/', 'name' => 'HTML格式化/压缩', 'accent' => ''],
            ['url' => '/formatcss/', 'name' => 'CSS格式化/压缩', 'accent' => '#f30'],
            ['url' => '/formatjs/', 'name' => 'JS格式化/压缩', 'accent' => ''],
            ['url' => '/endecodejs/', 'name' => 'JS加密/解密', 'accent' => ''],
            ['url' => '/confundirjs/', 'name' => 'JS代码混合加密', 'accent' => ''],
            ['url' => '/formatsql/', 'name' => 'SQL压缩/格式化', 'accent' => ''],
            ['url' => '/formatphp/', 'name' => 'PHP代码格式化工具', 'accent' => ''],
            ['url' => '/formatxml/', 'name' => 'XML压缩/格式化', 'accent' => ''],
            ['url' => '/formatcs/', 'name' => 'C#代码格式化工具', 'accent' => ''],
            ['url' => '/formatjava/', 'name' => 'JAVA代码格式化工具', 'accent' => ''],
            ['url' => '/formatcsql/', 'name' => 'SQL代码格式化工具', 'accent' => ''],
            ['url' => '/formatpy/', 'name' => 'Python代码格式化工具', 'accent' => ''],
            ['url' => '/formatruby/', 'name' => 'Ruby代码格式化工具', 'accent' => ''],
            ['url' => '/formatc/', 'name' => 'C语言代码格式化工具', 'accent' => ''],
            ['url' => '/formatcpp/', 'name' => 'C++代码格式化工具', 'accent' => ''],
            ['url' => '/formatperl/', 'name' => 'Perl代码格式化工具', 'accent' => ''],
            ['url' => '/formatvbs/', 'name' => 'VBScript格式化工具', 'accent' => ''],
            ['url' => '/html2js/', 'name' => 'Html转JS', 'accent' => ''],
            ['url' => '/htmloutjs/', 'name' => 'Html/JS互转', 'accent' => '#f30'],
            ['url' => '/htmlescape/', 'name' => 'Html转义工具', 'accent' => ''],
            ['url' => '/html2cj/', 'name' => 'Html转C#/JSP', 'accent' => ''],
            ['url' => '/html2php/', 'name' => 'Html转PHP代码', 'accent' => ''],
            ['url' => '/html2all/', 'name' => 'Html转ASP/Perl', 'accent' => ''],
            ['url' => '/htmlfromcsv/', 'name' => 'Excel转HTML表格', 'accent' => ''],
            ['url' => '/htmltable/', 'name' => 'Html表格生成器', 'accent' => ''],
            ['url' => '/html2ubb/', 'name' => 'HTML/UBB互转', 'accent' => ''],
            ['url' => '/htmlmarkdown/', 'name' => 'HTML/MarkDown互转', 'accent' => ''],
            ['url' => '/regex/', 'name' => '正则表达式测试工具', 'accent' => 'green'],
            ['url' => '/regexcode/', 'name' => '正则生成代码', 'accent' => ''],
            ['url' => '/formatfilter/', 'name' => 'Html过滤工具', 'accent' => ''],
            ['url' => '/regexdso/', 'name' => '常用正则表达式', 'accent' => ''],
            ['url' => '/regexsucha/', 'name' => '正则表达式语法速查', 'accent' => ''],
            ['url' => '/runjs/', 'name' => '运行Js/html/css', 'accent' => ''],
            ['url' => '/xpath/', 'name' => 'Xpath工具', 'accent' => ''],
        ],
    ],
    [
        'cat' => '加解密编码',
        'items' => [
            ['url' => '/md5/', 'name' => 'MD5加密工具', 'accent' => ''],
            ['url' => '/urlcode/', 'name' => 'URL网址16进制加密', 'accent' => ''],
            ['url' => '/urlthunder/', 'name' => '迅雷旋风URL加解密', 'accent' => ''],
            ['url' => '/base64/', 'name' => 'Base64加密/解密', 'accent' => ''],
            ['url' => '/escape/', 'name' => 'Escape加密/解密', 'accent' => ''],
            ['url' => '/deencrypt/', 'name' => '对称加密/解密', 'accent' => ''],
            ['url' => '/aesencrypt/', 'name' => 'AES加密/解密', 'accent' => ''],
            ['url' => '/desencrypt/', 'name' => 'DES加密/解密', 'accent' => ''],
            ['url' => '/rc4encrypt/', 'name' => 'RC4加密/解密', 'accent' => ''],
            ['url' => '/rabbitencrypt/', 'name' => 'Rabbit加密/解密', 'accent' => ''],
            ['url' => '/tripledes/', 'name' => 'TripleDES加密/解密', 'accent' => ''],
            ['url' => '/shaencrypt/', 'name' => 'SHA/SHA256加密', 'accent' => ''],
            ['url' => '/allencrypt/', 'name' => '散列/哈希加密大全', 'accent' => ''],
            ['url' => '/morse/', 'name' => '摩尔斯电码加解密', 'accent' => ''],
            ['url' => '/password/', 'name' => '密码生成器', 'accent' => ''],
            ['url' => '/uuid/', 'name' => 'UUID在线生成', 'accent' => ''],
            ['url' => '/guid/', 'name' => 'GUID在线生成', 'accent' => ''],
            ['url' => '/htpasswd/', 'name' => 'htpasswd生成', 'accent' => ''],
            ['url' => '/barcode/', 'name' => '条形码生成器', 'accent' => ''],
            ['url' => '/ip2long/', 'name' => 'IP/数字地址转换', 'accent' => ''],
            ['url' => '/img2base64/', 'name' => '图片转Base64', 'accent' => '#f00'],
            ['url' => '/utf8/', 'name' => 'UTF-8转GBK', 'accent' => ''],
            ['url' => '/unicode/', 'name' => 'Unicode/ASCII转换', 'accent' => ''],
            ['url' => '/ascii/', 'name' => 'ASCII编码/解码', 'accent' => ''],
            ['url' => '/urlencode/', 'name' => 'URL编码/解码', 'accent' => ''],
            ['url' => '/navtiveunicode/', 'name' => 'Native/Unicode编码转换', 'accent' => ''],
            ['url' => '/keyboardcode/', 'name' => 'KeyCode键盘按键码', 'accent' => ''],
            ['url' => '/androidkeycode/', 'name' => 'Android按键码', 'accent' => ''],
            ['url' => '/keyboardtest/', 'name' => '键盘测试工具', 'accent' => ''],
        ],
    ],
    [
        'cat' => '文本数字',
        'items' => [
            ['url' => '/editor/', 'name' => 'Html在线编辑器', 'accent' => ''],
            ['url' => '/autoformat/', 'name' => '文章自动排版', 'accent' => '#f30'],
            ['url' => '/caiji/', 'name' => '文章内容采集', 'accent' => 'green'],
            ['url' => '/jianfan/', 'name' => '简繁字体转换', 'accent' => ''],
            ['url' => '/pinyin/', 'name' => '汉字转为拼音', 'accent' => ''],
            ['url' => '/huoxingwen/', 'name' => '火星文转换器', 'accent' => ''],
            ['url' => '/txtreplace/', 'name' => '文本内容替换', 'accent' => ''],
            ['url' => '/textdiff/', 'name' => '文本内容对比', 'accent' => ''],
            ['url' => '/txtcount/', 'name' => '在线统计字数工具', 'accent' => ''],
            ['url' => '/shupai/', 'name' => '文字竖排工具', 'accent' => ''],
            ['url' => '/textflip/', 'name' => '文字翻转工具', 'accent' => ''],
            ['url' => '/quchong/', 'name' => '内容去重工具', 'accent' => ''],
            ['url' => '/wenzitexiao/', 'name' => '文字特效工具', 'accent' => ''],
            ['url' => '/zipstringtext/', 'name' => '字符串文本压缩工具', 'accent' => ''],
            ['url' => '/camelcase/', 'name' => '驼峰与下划线互转', 'accent' => 'blue'],
            ['url' => '/quanbaojiao/', 'name' => '全角半角转换', 'accent' => ''],
            ['url' => '/enlower/', 'name' => '英文字母大小写转换', 'accent' => ''],
            ['url' => '/rmbdaxie/', 'name' => '人民币大写转换工具', 'accent' => ''],
            ['url' => '/random/', 'name' => '随机数生成器', 'accent' => ''],
            ['url' => '/unixtime/', 'name' => 'Unix时间戳在线转换', 'accent' => ''],
            ['url' => '/hexconvert/', 'name' => '常用进制转换工具', 'accent' => ''],
            ['url' => '/hexrgb/', 'name' => 'RGB颜色在线转换', 'accent' => ''],
        ],
    ],
    [
        'cat' => '网络',
        'items' => [
            ['url' => '/ip/', 'name' => 'IP地址归属地查询', 'accent' => ''],
            ['url' => '/websocket/', 'name' => 'Websocket测试', 'accent' => ''],
            ['url' => '/browserinfo/', 'name' => '获取浏览器信息', 'accent' => ''],
            ['url' => '/dns/', 'name' => '公共DNS', 'accent' => ''],
            ['url' => '/alldns/', 'name' => '各地区公共DNS', 'accent' => ''],
            ['url' => '/dnsdx/', 'name' => '各地电信DNS', 'accent' => ''],
            ['url' => '/dnslt/', 'name' => '各地联通DNS', 'accent' => ''],
            ['url' => '/dnsyd/', 'name' => '各地移动DNS', 'accent' => ''],
            ['url' => '/dnstt/', 'name' => '各地铁通DNS', 'accent' => ''],
            ['url' => '/dnsedu/', 'name' => '教育网DNS', 'accent' => ''],
            ['url' => '/dnsusa/', 'name' => '美国DNS', 'accent' => ''],
        ],
    ],
    [
        'cat' => '站长',
        'items' => [
            ['url' => '/checkweixin/', 'name' => '微信域名检测工具', 'accent' => 'red'],
            ['url' => '/htaccess2nginx/', 'name' => 'htaccess转nginx', 'accent' => 'green'],
            ['url' => '/shortcut/', 'name' => '生成桌面快捷方式', 'accent' => ''],
            ['url' => '/px2rem/', 'name' => 'rem与px转换工具', 'accent' => ''],
            ['url' => '/favicon/', 'name' => '在线制作ico图标', 'accent' => ''],
            ['url' => '/createmeta/', 'name' => '生成网页Meta标签', 'accent' => ''],
            ['url' => '/refresh/', 'name' => '在线定时刷新网址', 'accent' => ''],
            ['url' => '/tiaoseban/', 'name' => '在线调色板', 'accent' => ''],
            ['url' => '/gzip/', 'name' => '网站Gzip压缩检测', 'accent' => ''],
            ['url' => '/checkurl/', 'name' => '网站死链检测', 'accent' => ''],
            ['url' => '/whois/', 'name' => 'Whois查询工具', 'accent' => ''],
            ['url' => '/chaicp/', 'name' => 'ICP网站备案查询', 'accent' => ''],
            ['url' => '/chameta/', 'name' => 'Meta标签优化分析', 'accent' => ''],
            ['url' => '/checkkeyword/', 'name' => '网页关键词密度检测', 'accent' => ''],
            ['url' => '/webstatus/', 'name' => 'HTTP状态码查询', 'accent' => ''],
        ],
    ],
    [
        'cat' => '计算',
        'items' => [
            ['url' => '/nianlvli/', 'name' => '利率计算器在线', 'accent' => ''],
            ['url' => '/subnetmask/', 'name' => '子网掩码计算器', 'accent' => ''],
            ['url' => '/calculator/', 'name' => '在线科学计算器', 'accent' => ''],
            ['url' => '/calcarea/', 'name' => '面积换算器', 'accent' => ''],
            ['url' => '/calcheat/', 'name' => '热量换算器', 'accent' => ''],
            ['url' => '/calcvolume/', 'name' => '体积换算器', 'accent' => ''],
            ['url' => '/calcpressure/', 'name' => '压力换算器', 'accent' => ''],
            ['url' => '/calcpower/', 'name' => '功率换算器', 'accent' => ''],
            ['url' => '/calclength/', 'name' => '长度换算器', 'accent' => ''],
            ['url' => '/calctemperature/', 'name' => '温度换算器', 'accent' => ''],
            ['url' => '/calctime/', 'name' => '时间换算器', 'accent' => ''],
            ['url' => '/calcspeed/', 'name' => '速度换算器', 'accent' => ''],
            ['url' => '/calcangle/', 'name' => '角度换算器', 'accent' => ''],
            ['url' => '/calcdata/', 'name' => '数据大小换算器', 'accent' => ''],
            ['url' => '/calcthickness/', 'name' => '密度换算器', 'accent' => ''],
            ['url' => '/calcforce/', 'name' => '力换算器', 'accent' => ''],
        ],
    ],
    [
        'cat' => '其他',
        'items' => [
            ['url' => '/tuya/', 'name' => '在线涂鸦画板', 'accent' => ''],
            ['url' => '/shizhong/', 'name' => '在线时钟', 'accent' => ''],
            ['url' => '/worldtime/', 'name' => '世界各地时间', 'accent' => ''],
            ['url' => '/capital/', 'name' => '世界各国首都查询', 'accent' => ''],
            ['url' => '/currency/', 'name' => '世界各地货币查询', 'accent' => ''],
            ['url' => '/areacode/', 'name' => '世界各国区号时差查询', 'accent' => ''],
            ['url' => '/jieri/', 'name' => '世界节日查询', 'accent' => ''],
            ['url' => '/shaoshuminzu/', 'name' => '全国少数民族分布查询', 'accent' => ''],
            ['url' => '/chaodai/', 'name' => '中国历史朝代时间查询表', 'accent' => ''],
            ['url' => '/tesufuhao/', 'name' => '特殊符号大全', 'accent' => ''],
            ['url' => '/lishishangdejintian/', 'name' => '历史上的今天', 'accent' => ''],
        ],
    ],
    [
        'cat' => '对照列表',
        'items' => [
            ['url' => '/useragent/', 'name' => '常用User-Agent', 'accent' => ''],
            ['url' => '/contenttype/', 'name' => 'Content-Type对照表', 'accent' => ''],
            ['url' => '/requestmethod/', 'name' => 'Request请求大全', 'accent' => ''],
            ['url' => '/httpheader/', 'name' => 'HTTP请求头大全', 'accent' => ''],
            ['url' => '/pagecode/', 'name' => 'HTTP状态码', 'accent' => ''],
            ['url' => '/asciicode/', 'name' => 'ASCII对照表', 'accent' => ''],
            ['url' => '/htmlescapechar/', 'name' => 'HTML特殊字符转义', 'accent' => ''],
            ['url' => '/ports/', 'name' => '常见端口大全', 'accent' => ''],
            ['url' => '/bootstrapicon/', 'name' => 'Bootstrap字体图标', 'accent' => ''],
            ['url' => '/androidmanifest/', 'name' => 'Android Manifest权限大全', 'accent' => ''],
            ['url' => '/linuxcmd/', 'name' => 'Linux常用命令大全', 'accent' => ''],
        ],
    ],
];
